name: RandomSpawn
version: 1.0
author: Nic Bestauros
main: com.Bestauros.RandomSpawn.Main
commands:
  RandomSpawn:
    description: Spawns the player within -5000,5000 on x and y.
    usage: /RandomSpawn